[package]
name = "pichain-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
pichain-types = { path = "../crates/pichain-types" }
pichain-crypto = { path = "../crates/pichain-crypto" }
serde_json = "1"

[[bin]]
name = "tx_deserialize"
path = "fuzz_targets/tx_deserialize.rs"
doc = false

[[bin]]
name = "block_deserialize"
path = "fuzz_targets/block_deserialize.rs"
doc = false
