#!/usr/bin/env bash
#
# PIChain Devnet Key Generator
# Generates 3 validator key sets and produces per-node TOML config files
# with cross-referenced bootstrap_peers and genesis_validators.
#
# Usage:
#   ./scripts/generate-devnet-keys.sh [output_dir]
#
# Output:
#   {output_dir}/node1.toml  — config for validator 1
#   {output_dir}/node2.toml  — config for validator 2
#   {output_dir}/node3.toml  — config for validator 3
#   {output_dir}/keys/       — validator key files (validator.key per node)
#
set -euo pipefail

PICHAIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="${1:-${PICHAIN_DIR}/devnet-config}"
BINARY="${PICHAIN_DIR}/target/release/pichain"
NUM_NODES=3
CHAIN_ID=31415
BASE_RPC_PORT=8314
BASE_P2P_PORT=9314

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}=== PIChain Devnet Key Generator ===${NC}"

# Check binary exists
if [ ! -f "$BINARY" ]; then
    echo -e "${RED}Binary not found at ${BINARY}${NC}"
    echo "Build first: cargo build --release"
    exit 1
fi

# Create output directories
mkdir -p "${OUTPUT_DIR}/keys"
echo "Output directory: ${OUTPUT_DIR}"

# Arrays to hold generated values
declare -a ADDRESSES
declare -a BLS_PUBKEYS
declare -a BLS_POPS
declare -a PEER_IDS
declare -a ED25519_SECRETS
declare -a BLS_SECRETS

# --- Step 1: Generate keys for each node ---
echo ""
echo -e "${CYAN}Generating ${NUM_NODES} validator key sets...${NC}"

for i in $(seq 1 $NUM_NODES); do
    echo "  Node ${i}:"

    # Run keygen and capture output
    KEYGEN_OUTPUT=$("${BINARY}" keygen 2>/dev/null)

    # Parse output
    ADDRESS=$(echo "$KEYGEN_OUTPUT" | grep "^Address:" | awk '{print $2}')
    SECRET=$(echo "$KEYGEN_OUTPUT" | grep "^Secret Key:" | awk '{print $3}')
    BLS_PUB=$(echo "$KEYGEN_OUTPUT" | grep "^BLS Public:" | awk '{print $3}')
    BLS_POP=$(echo "$KEYGEN_OUTPUT" | grep "^BLS PoP:" | awk '{print $3}')
    BLS_SEC=$(echo "$KEYGEN_OUTPUT" | grep "^BLS Secret:" | awk '{print $3}')
    PEER_ID=$(echo "$KEYGEN_OUTPUT" | grep "^Peer ID:" | awk '{print $3}')

    if [ -z "$ADDRESS" ] || [ -z "$SECRET" ] || [ -z "$BLS_PUB" ] || [ -z "$PEER_ID" ]; then
        echo -e "${RED}    Failed to parse keygen output for node ${i}${NC}"
        echo "$KEYGEN_OUTPUT"
        exit 1
    fi

    # Extract hex address (remove 0x prefix if present)
    ADDR_HEX=$(echo "$ADDRESS" | sed 's/^0x//')

    ADDRESSES+=("$ADDR_HEX")
    ED25519_SECRETS+=("$SECRET")
    BLS_PUBKEYS+=("$BLS_PUB")
    BLS_POPS+=("${BLS_POP:-}")
    PEER_IDS+=("$PEER_ID")

    BLS_SECRETS+=("${BLS_SEC:-}")

    echo "    Address:  ${ADDRESS}"
    echo "    Peer ID:  ${PEER_ID}"
    echo -e "    ${GREEN}OK${NC}"

    # Save the full keygen output for reference
    echo "$KEYGEN_OUTPUT" > "${OUTPUT_DIR}/keys/node${i}-keygen.txt"
done

# --- Step 2: Generate per-node TOML configs ---
echo ""
echo -e "${CYAN}Generating per-node TOML configs...${NC}"

for i in $(seq 1 $NUM_NODES); do
    IDX=$((i - 1))
    CONFIG_FILE="${OUTPUT_DIR}/node${i}.toml"

    cat > "$CONFIG_FILE" <<EOF
# PIChain Devnet — Node ${i} Configuration
# Auto-generated by generate-devnet-keys.sh

data_dir = "/data"
rpc_addr = "0.0.0.0:${BASE_RPC_PORT}"
p2p_addr = "/ip4/0.0.0.0/tcp/${BASE_P2P_PORT}"
chain_id = ${CHAIN_ID}
max_mempool_size = 100000
validator_stake_pi = 100000
log_level = "info"

# Bootstrap peers — connect to the other validators
bootstrap_peers = [
EOF

    # Add all OTHER nodes as bootstrap peers
    for j in $(seq 1 $NUM_NODES); do
        if [ "$j" -ne "$i" ]; then
            JIDX=$((j - 1))
            # Use Docker service names with /dns4/ (libp2p resolves hostnames via DNS)
            echo "    \"/dns4/pichain-node${j}/tcp/${BASE_P2P_PORT}/p2p/${PEER_IDS[$JIDX]}\"," >> "$CONFIG_FILE"
        fi
    done

    cat >> "$CONFIG_FILE" <<EOF
]

# Genesis validators — all validators in the network
EOF

    # Add all OTHER nodes as genesis validators
    for j in $(seq 1 $NUM_NODES); do
        if [ "$j" -ne "$i" ]; then
            JIDX=$((j - 1))
            cat >> "$CONFIG_FILE" <<EOF

[[genesis_validators]]
address = "${ADDRESSES[$JIDX]}"
stake_pi = 100000
bls_public_key = "${BLS_PUBKEYS[$JIDX]}"
EOF
            # Add bls_pop if available
            if [ -n "${BLS_POPS[$JIDX]}" ]; then
                echo "bls_pop = \"${BLS_POPS[$JIDX]}\"" >> "$CONFIG_FILE"
            fi
        fi
    done

    echo "  ${CONFIG_FILE}"
done

# --- Step 3: Create validator.key files for each node ---
echo ""
echo -e "${CYAN}Creating validator key files...${NC}"

for i in $(seq 1 $NUM_NODES); do
    IDX=$((i - 1))
    KEY_DIR="${OUTPUT_DIR}/keys/node${i}"
    mkdir -p "$KEY_DIR"

    ED_SECRET="${ED25519_SECRETS[$IDX]}"
    BLS_SEC="${BLS_SECRETS[$IDX]}"

    if [ -z "$ED_SECRET" ] || [ -z "$BLS_SEC" ]; then
        echo -e "  ${RED}Node ${i}: failed to capture keys — check keygen output${NC}"
        cat "${OUTPUT_DIR}/keys/node${i}-keygen.txt"
        exit 1
    fi

    cat > "${KEY_DIR}/validator.key" <<EOF
{
  "ed25519_secret": "${ED_SECRET}",
  "bls_secret": "${BLS_SEC}"
}
EOF
    chmod 600 "${KEY_DIR}/validator.key"
    echo "  Node ${i}: ${KEY_DIR}/validator.key"
done

# --- Step 4: Print summary ---
echo ""
echo -e "${GREEN}=== Devnet Configuration Complete ===${NC}"
echo ""
echo "Nodes:"
for i in $(seq 1 $NUM_NODES); do
    IDX=$((i - 1))
    echo "  Node ${i}:"
    echo "    Address:  ${ADDRESSES[$IDX]}"
    echo "    Peer ID:  ${PEER_IDS[$IDX]}"
    echo "    Config:   ${OUTPUT_DIR}/node${i}.toml"
    echo "    RPC:      http://localhost:$((BASE_RPC_PORT + i - 1))"
done
echo ""
echo "To start the devnet:"
echo "  docker compose up -d"
echo ""
echo "To verify:"
echo "  ./scripts/multi-node-test.sh"
